spring:
  application:
    name: accounts

server:
  port: 8080                     # port aplikacji (opcjonalnie)
  error:
    include-message: always      # pokazuj treść błędu w odpowiedzi (pomocne przy dev)

logging:
  level:
    org.hibernate.SQL: DEBUG     # logowanie zapytań SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

build:
  version: 1.0

accounts:
  message: "Welcome"
  contact:
    name: "Adam"
    email: "adam@example.com"
  onCallSupport:
    - 111111111
    - 222222222
