server:
  port: 9000
spring:
  application:
    name: cards

build:
  version: 1.0

loans:
  message: "Welcome"
  contact:
    name: "Adam"
    email: "adam@example.com"
  onCallSupport:
    - 111111111
    - 222222222
