server:
  port: 8090
spring:
  application:
    name: loans


build:
  version: 1.0

accounts:
  message: "Welcome"
  contact:
    name: "Adam"
    email: "adam@example.com"
  onCallSupport:
    - 111111111
    - 222222222
